name: Run Daily Tasks

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print dotnet version
        run: dotnet --info

      - name: Checkout Docs
        uses: actions/checkout@v4
        with:
          path: velopack.docs

      - name: Checkout Velopack
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: velopack/velopack
          path: velopack

      - name: Checkout Fusion
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: velopack/velopack.fusion
          path: velopack.fusion

      - name: Install dotnet tools
        run: dotnet tool install -g docfx

      - name: Install dependencies
        working-directory: velopack.docs
        run: npm ci

      - name: Run Tasks
        working-directory: velopack.docs
        run: npm run daily-tasks

      - uses: actions4git/add-commit-push@v1
        with:
          path: velopack.docs
          commit-author: github-actions
          commit-message: "Update translations / reference libraries"

